/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "app.h"
#include <cassert>

int main() {
    cpp_learn::Greeter greeter;
    assert(greeter.greeting() == "Hello, World!");
    return 0;
}
